### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by vikasg603** [Jamminroot/todo-2-gh-issue#6]
On August 16th, 2020 at 17:18 (UTC) your personal access token (GithubTodoToIssue) using RestSharp/106.0.0.0 was used as part of a query parameter to access an endpoint through the GitHub API:

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

**Comment by Jamminroot** [comment]
Pushed new update which fixes API usage (along with a few other changes).
https://github.com/Jamminroot/todo-2-gh-issue/releases/tag/1.1.5
Closing the issue.

**Comment by vikasg603** [comment]
Now It's working just fine.
Thanks.

**Comment by Jamminroot** [comment]
Forgot to mention here, too - after I pushed initial update with 1.1.5, I forgot to update a few API usages; Make sure to update to the new version now (it also brings a few good features anyway).
